### ISSUE TITLE
[Opt] do not parse giant JSON string for each query

### ISSUE THREAD

**Issue by wbrickner** [grantshandy/webster-rs#1]
Hi, 

I am wondering if a PR would be accepted that changes the behavior from reparsing a giant JSON file every query to something better but more complex. 

The idea is to store compressed bytes as a static, in the binary as you have done now.

The first dictionary access decompresses the bytes and stores them in a `lazy_static` BTree for low memory usage and high data locality and O(log n) access complexity.

This would incur a small startup cost, but this startup cost is likely similar to the cost of every single call that we have now. This solution would be very fast for subsequent accesses and reduce binary bloat.

**Comment by grantshandy** [comment]
Absolutley that sounds like a great idea. I'd definitely accept a PR like that.

**Comment by grantshandy** [comment]
@wbrickner I've done what I think you were talking about here:
```rust
lazy_static! {
    static ref DICT: Value = serde_json::from_str(include_str!("dictionary.json")).unwrap_or(Value::from(""));
}
```
I've created tests that each search up five different definitions with one being the new and one being the old method.

The old method takes 5.23 seconds, while the new one you recommended only takes 0.91 seconds. 

I think this is what you were talking about, is there anything I should add or should I close the issue?

**Comment by wbrickner** [comment]
The remaining optimizations I'm working on reduce memory usage at runtime and reduce binary size via gzip compression, using automatic recompression when the dictionary changes. 

The serde representation of the dictionary is probably very slow relative to something like a BTreeMap, so that should speed up the amortized access times more.

**Comment by grantshandy** [comment]
Ah okay sounds great.

Well when you feel it's ready put in a pull request and I'll have a look over it :)
